### ISSUE TITLE
Arquivo Retorno Caixa

### ISSUE THREAD

**Issue by fabiopneves** [controlid/Exemplos-dedicados-a-linha-Acesso#2]
Estou com Problema arquivo retorno da caixa, pois as data em que o arquivo tras nao esta trazendo as data certa, me parece que falta leitura no segmento U.
Preciso pegar a data de Pagamento, 

16.3U Data da Ocorrência Data da Ocorrência
17.3U Data do Crédito Data da Efetivação do Crédito

[RETORNOCEF170916.txt](https://github.com/controlid/iDAccess/files/495543/RETORNOCEF170916.txt)

**Comment by mguardarini** [comment]
Olá Fabio, tudo bem? 

Peço que entre em contato com o suporte técnico da Control iD para verificar o arquivo exportado.

Tel:  SP 11 3059 - 9900 

Atenciosamente:

**Comment by impactro** [comment]
Ola,, você abriu o suporte no link errado,
https://github.com/impactro/Boleto-Test/issues
