### ISSUE TITLE
Comando invalido ao executar acão

### ISSUE THREAD

**Issue by uizzycleverson** [controlid/Exemplos-dedicados-a-linha-Acesso#3]
usando o código de exemplo do Wiki:
$.ajax({
	url: "/execute_actions.fcgi?session=" + session,
	type: 'POST',
	contentType: 'application/json',
	data: JSON.stringify({
		actions: [ { action: "door", parameters: "door=1" } ]
	})
});

retorna = {error : "Invalid command: execute_actions"}

**Comment by albert-controlid** [comment]
Obrigado pela mensagem. Por favor entre em contato com o nosso suporte (www.controlid.com.br/contato) e peça para conversar com o nosso departamento de integração.
